<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Lab5.QMS</RootNamespace>
    <AssemblyName>Lab5.QMS</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Company>Lab5</Company>
    <Product>Lab5.QMS</Product>
    <Description>Acumatica QMS customization 22.200.001</Description>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
</Project>
